### ISSUE TITLE
Check for no archived users

### ISSUE THREAD

**Issue by 7h3blu3** [7h3blu3/assessment-frontend#1]
There should be a message saying no archived users instead of showing empty table

![image](https://user-images.githubusercontent.com/22320693/181452248-a2a72114-4b07-4b5a-aae6-9f604b4f4215.png)

Should be like the one for archived scenarios

![image](https://user-images.githubusercontent.com/22320693/181452326-29fe0674-e72f-4abc-aae5-b0ff1edcc967.png)

**Comment by Fattic** [comment]
Done.
