### ISSUE TITLE
Check for no Submitted Scenarios

### ISSUE THREAD

**Issue by 7h3blu3** [7h3blu3/assessment-frontend#3]
Similar to https://github.com/7h3blu3/assessment-frontend/issues/1 - [Check for no archived users #1] we should add a message saying no Submitted Scenarios in User Submission page

![image](https://user-images.githubusercontent.com/22320693/181453223-c9cbb85d-2753-4f8d-8f3a-ced279b5957d.png)

**Comment by Fattic** [comment]
Created the check for no Submitted Scenarios.
